FileVersion = 1
Projects = {Nanoforge = {Path = "."}, RfgTools = {Path = "Dependencies/RfgTools"}, "Beef.Linq" = {Path = "Dependencies/Beef.Linq/src"}, ImGui = {Path = "Dependencies/imgui-beef"}, Common = {Path = "Dependencies/Common"}, Zlib = {Path = "Dependencies/RfgTools/Dependencies/ZlibBeef"}, bon = {Path = "Dependencies/bon"}, nativefiledialog-beef = {Path = "Dependencies/nativefiledialog-beef"}}

[Workspace]
StartupProject = "Nanoforge"
PreprocessorMacros = ["BON_PROVIDE_ERROR_MESSAGE"]

[Configs.Debug.Win64]
BfSIMDSetting = "SSE4"

[Configs.Release.Win64]
Toolset = "Microsoft"
BfSIMDSetting = "SSE4"
LTOType = "None"

[Configs.Release.Win32]
Toolset = "Microsoft"

[Configs.Paranoid.Win64]
BfSIMDSetting = "SSE4"

[Configs.Test.Win64]
BfSIMDSetting = "SSE4"
