FileVersion = 1
Dependencies = {corlib = "*", RfgTools = "*", "Beef.Linq" = "*", ImGui = "*", bon = "*"}

[Project]
Name = "Nanoforge"
TargetType = "BeefGUIApplication"
StartupObject = "Nanoforge.Program"
